From bugs+caf_=bugs=bugs.plt-scheme.org@plt-scheme.org Fri Oct  4 23:04:42 2013
Received: from mail-oa0-f54.google.com (mail-oa0-f54.google.com [209.85.219.54])
	by winooski.ccs.neu.edu (8.14.7/8.14.7) with ESMTP id r9534edw005603
	for <bugs@bugs.plt-scheme.org>; Fri, 4 Oct 2013 23:04:41 -0400
Message-Id: <201310050238.r952chq4004012@winooski.ccs.neu.edu>
Date: Fri, 4 Oct 2013 22:38:43 -0400
From: eric.n.dobson@gmail.com
To: bugs@racket-lang.org
Subject: contract-out with struct gives error messages with bad name

>Number:         14073
>Category:       contract
>Synopsis:       contract-out with struct gives error messages with bad name
>Class:          sw-bug
>Responsible:    robby
>Severity:       serious
>Priority:       medium
>State:          closed
>Confidential:   no
>Arrival-Date:   Fri Oct 04 23:08:01 -0400 2013
>Closed-Date:    Sun Oct 06 09:22:02 -0400 2013
>Last-Modified:  Sun Oct 06 09:22:02 -0400 2013
>Originator:     Eric Dobson
>Organization:
plt
>Submitter-Id:   unknown
>Release:        HEAD
>Environment:
MacIntel / Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.28 (KHTML, like Gecko) Chrome/26.0.1397.2 Safari/537.28
>Description:
I expect to get an error message about foo having an arity mismatch and instead I get an error message about foo3.
>How-To-Repeat:
Welcome to Racket v5.90.0.9.
-> (module foo racket
     (struct foo ())
     (provide (contract-out (struct foo ()))))
-> (require 'foo)
-> (foo 2)
; foo3: arity mismatch;
;  the expected number of arguments does not match the given number
;   expected: 0
;   given: 1
; [,bt for context]
-> 
>Fix:
>Audit-Trail:
State changed from "open" to "closed" by robby@racket-lang.org at Sun, 06 Oct 2013 09:22:02 -0400
Reason>>> A commit by robby@racket-lang.org has resolved this report
  http://git.racket-lang.org/plt/commit/a13aed7420
  | fix name of struct constructor built by struct-out
  | 
  | closes PR 14073

